spring.datasource.url=jdbc:mysql://localhost:3306/demo_video_games_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=app_user
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Inicialización de la base de datos
spring.sql.init.mode=always
spring.sql.init.platform=mysql

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf configuration (optional, usually default is fine)
spring.thymeleaf.cache=false
